export default [
    // 'Completed' routes from this week
    {
      id: 1,
      start_city: 'Kyiv',
      end_city: 'Lviv',
      distance: 500,
      departure_date: new Date(2023, 6, 10),
      completion_date: new Date(2023, 6, 14),
      transport_type: 'cargo',
      expected_revenue: 1000,
      transport_id: 5,
      status: 'completed',
    },
    {
      id: 2,
      start_city: 'Lviv',
      end_city: 'Odesa',
      distance: 800,
      departure_date: new Date(2023, 6, 11),
      completion_date: new Date(2023, 6, 15),
      transport_type: 'cargo',
      expected_revenue: 1500,
      transport_id: 6,
      status: 'completed',
    },
    {
      id: 3,
      start_city: 'Kyiv',
      end_city: 'Kharkiv',
      distance: 400,
      departure_date: new Date(2023, 6, 12),
      completion_date: new Date(2023, 6, 16),
      transport_type: 'passenger',
      expected_revenue: 800,
      transport_id: 7,
      status: 'completed',
    },
    {
      id: 4,
      start_city: 'Kharkiv',
      end_city: 'Dnipro',
      distance: 200,
      departure_date: new Date(2023, 6, 13),
      completion_date: new Date(2023, 6, 17),
      transport_type: 'passenger',
      expected_revenue: 500,
      transport_id: 8,
      status: 'completed',
    },
    // 'Ongoing' routes for next 7 days
    {
      id: 5,
      start_city: 'Odesa',
      end_city: 'Kyiv',
      distance: 500,
      departure_date: new Date(2023, 6, 17),
      completion_date: new Date(2023, 6, 23),
      transport_type: 'cargo',
      expected_revenue: 1200,
      transport_id: 1,
      status: 'ongoing',
    },
    {
      id: 6,
      start_city: 'Lviv',
      end_city: 'Kharkiv',
      distance: 800,
      departure_date: new Date(2023, 6, 18),
      completion_date: new Date(2023, 6, 24),
      transport_type: 'cargo',
      expected_revenue: 1500,
      transport_id: 2,
      status: 'ongoing',
    },
    {
      id: 7,
      start_city: 'Kyiv',
      end_city: 'Odesa',
      distance: 400,
      departure_date: new Date(2023, 6, 19),
      completion_date: new Date(2023, 6, 25),
      transport_type: 'passenger',
      expected_revenue: 800,
      transport_id: 3,
      status: 'ongoing',
    },
    {
      id: 8,
      start_city: 'Dnipro',
      end_city: 'Kyiv',
      distance: 300,
      departure_date: new Date(2023, 6, 20),
      completion_date: new Date(2023, 6, 26),
      transport_type: 'passenger',
      expected_revenue: 700,
      transport_id: 4,
      status: 'ongoing',
    },
    // 'Pending' routes for in a week (2 don't have attached transport)
    {
      id: 9,
      start_city: 'Kyiv',
      end_city: 'Odesa',
      distance: 500,
      departure_date: new Date(2023, 6, 24),
      completion_date: new Date(2023, 6, 30),
      transport_type: 'cargo',
      expected_revenue: 1200,
      transport_id: null,
      status: 'pending',
    },
    {
      id: 10,
      start_city: 'Lviv',
      end_city: 'Kharkiv',
      distance: 800,
      departure_date: new Date(2023, 6, 25),
      completion_date: new Date(2023, 6, 31),
      transport_type: 'cargo',
      expected_revenue: 1500,
      transport_id: null,
      status: 'pending',
    },
    {
      id: 11,
      start_city: 'Kyiv',
      end_city: 'Odesa',
      distance: 400,
      departure_date: new Date(2023, 6, 26),
      completion_date: new Date(2023, 7, 1),
      transport_type: 'passenger',
      expected_revenue: 800,
      transport_id: 8,
      status: 'pending',
    },
    {
      id: 12,
      start_city: 'Dnipro',
      end_city: 'Kyiv',
      distance: 300,
      departure_date: new Date(2023, 6, 27),
      completion_date: new Date(2023, 7, 2),
      transport_type: 'passenger',
      expected_revenue: 700,
      transport_id: 9,
      status: 'pending',
    },
  ];
  