export default [
    // Transports attached to 'ongoing' routes, status 'busy'
    {
      id: 1,
      plate_number: 'AA1234BB',
      status: 'busy',
      model: 'Volvo FH',
      purchase_date: new Date(2021, 0, 1),
      mileage: 20000,
      transport_type: 'cargo',
    },
    {
      id: 2,
      plate_number: 'AA2345CC',
      status: 'busy',
      model: 'Mercedes-Benz Actros',
      purchase_date: new Date(2021, 6, 1),
      mileage: 30000,
      transport_type: 'cargo',
    },
    {
      id: 3,
      plate_number: 'BB5678DD',
      status: 'busy',
      model: 'Scania R-series',
      purchase_date: new Date(2022, 3, 1),
      mileage: 15000,
      transport_type: 'passenger',
    },
    {
      id: 4,
      plate_number: 'CC9012EE',
      status: 'busy',
      model: 'MAN TGX',
      purchase_date: new Date(2022, 9, 1),
      mileage: 10000,
      transport_type: 'passenger',
    },
    // Transports attached to 'pending' routes, status 'free'
    {
      id: 5,
      plate_number: 'DD3456FF',
      status: 'free',
      model: 'Toyota Camry',
      purchase_date: new Date(2020, 5, 1),
      mileage: 5000,
      transport_type: 'cargo',
    },
    {
      id: 6,
      plate_number: 'EE7890GG',
      status: 'free',
      model: 'BMW X5',
      purchase_date: new Date(2020, 8, 1),
      mileage: 10000,
      transport_type: 'passenger',
    },
    // Transports not attached to any routes
    {
      id: 7,
      plate_number: 'FF1234HH',
      status: 'free',
      model: 'Iveco Stralis',
      purchase_date: new Date(2021, 2, 1),
      mileage: 25000,
      transport_type: 'cargo',
    },
    {
      id: 8,
      plate_number: 'GG2345II',
      status: 'free',
      model: 'Renault Magnum',
      purchase_date: new Date(2021, 4, 1),
      mileage: 27000,
      transport_type: 'cargo',
    },
    {
      id: 9,
      plate_number: 'HH5678JJ',
      status: 'free',
      model: 'Ford Mondeo',
      purchase_date: new Date(2020, 7, 1),
      mileage: 12000,
      transport_type: 'passenger',
    },
  ];
